### ISSUE TITLE
bundler: command not found: db:collision_test

### ISSUE THREAD

**Issue by liaoziyang** [alextsui05/rails-4-mysql-index-problem#3]
`bundler: command not found: db:collision_test`が発生しました。

**Comment by alextsui05** [comment]
@liaoziyang すみません、打ち込み間違えました。正解はこれはずです：

```
bundle exec rake db:collision_test
```

ちなみに、コードはlib/tasksに見れますので、そちらのファイルをご参考までに。

**Comment by liaoziyang** [comment]
@alextsui05 できました！
